# Generated by Django 2.2 on 2019-09-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
