# Generated by Django 2.2 on 2019-09-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20190924_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
